name: Deploy NextJS Blog to GitHub Pages

on:
  # 支持手动触发
  workflow_dispatch:
  # 当推送到 nextjs-theme 分支时触发
  push:
    branches:
      - nextjs-theme
  # 当创建到 nextjs-theme 分支的 pull request 时触发
  pull_request:
    branches:
      - nextjs-theme

permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时运行一个部署，跳过正在运行和挂起的运行
concurrency:
  group: "nextjs-blog-pages"
  cancel-in-progress: false

jobs:
  # 构建作业
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npx next build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # 部署作业
  deploy:
    # 移除环境限制以避免分支保护规则问题
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4